### ISSUE TITLE
New plugin added

### ISSUE THREAD

**Issue by StoneyStoner** [StoneworksMC/API-Docs#3]
Gaming

**Comment by UndyeMC** [comment]
No gaming

**Comment by UndyeMC** [comment]
Wait this shows up in #dev-feed

**Comment by UndyeMC** [comment]
Hello, person reading this

**Comment by StoneyStoner** [comment]
Hi undiemc

**Comment by UndyeMC** [comment]
Hello StoneyStoner

**Comment by UndyeMC** [comment]
Based

**Comment by UndyeMC** [comment]
Hi Hjonk

**Comment by StoneyStoner** [comment]
I 🧑‍🦲 LOVE 😍 DUTY <:DUTY:1017448924983869460> 
I SIMPLY 🤫 CANNOT ⛔ GET ENOUGH 🤑 OF IT 😩 
I 🧑‍🦲 PRAISE 🙏 BAREND 💪 AND GBN 🐒 DAILY 🫡 
THERE ☝️ IS NOTHING ❌ I WOULD NOT DO 😤 FOR DUTY <:DUTY:1017448924983869460>

**Comment by UndyeMC** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO IT DOESNT SHOW UP ANYMORE
